### ISSUE TITLE
.a.lengthOf() error

### ISSUE THREAD

**Issue by alexwhitman** [tj/should.js#102]
`[].should.have.length(0)` is fine.
`[].should.have.lengthOf(0)` is fine.
`[].should.have.a.lengthOf(0)` gives:

```
     TypeError: Object function (type, desc){
    this.assert(
        type == typeof this.obj
      , function(){ return 'expected ' + this.inspect + ' to be a ' + type + (desc ? " | " + desc : "") }
      , function(){ return 'expected ' + this.inspect + ' not to be a ' + type  + (desc ? " | " + desc : "") })
    return this;
  } has no method 'lengthOf'
```

**Comment by ifraixedes** [comment]
+1

**Comment by btd** [comment]
It is because `.a` it is method to check `typeof`. It is covered in docs.

**Comment by ifraixedes** [comment]
That's all right, but then it is needed to remove from README that line which is in "Length" section: https://github.com/visionmedia/should.js#length

**Comment by btd** [comment]
Yes, you right. I will fix it. I will reopen it for now, I have some idea about `a`.

**Comment by btd** [comment]
Fixed in v2.
