### ISSUE TITLE
Documentation, keys API

### ISSUE THREAD

**Issue by calvernaz** [tj/should.js#108]
I don't know if it is a typo or just a bad example of API usage, but anyway, I believe it could be,

From wiki documentation:
var obj = { foo: 'bar', baz: 'raz' };
obj.should.have.keys('foo', 'bar');
obj.should.have.keys(['foo', 'bar']);

could be: 
var obj = { foo: 'bar', baz: 'raz' };
obj.should.have.keys('foo', 'baz');
obj.should.have.keys(['foo', 'baz']);

**Comment by btd** [comment]
Thanks.
