### ISSUE TITLE
No way to test an array of properties non inclusively

### ISSUE THREAD

**Issue by olalonde** [tj/should.js#113]
Would be nice to have should.have.keys(keys) but where keys is a non exhaustive list of keys. Right now, it fails if keys doesn't contain every single keys that the object has.

My workaround for now is:

``` javascript
['user', 'email', 'name'].forEach(function (property) {
  user.should.have.property(property);
});
```

Also - and maybe  this should be a separate issue - why can't I chain this way?

``` javascript
user.should.have.property('username').and.have.property('email');
```

**Comment by btd** [comment]
in v2 will be `properties(name1, name2,. ..)`
