### ISSUE TITLE
add "sorted" 

### ISSUE THREAD

**Issue by erelsgl** [tj/should.js#123]
I want to compare two arrays, A and B, regardless of order.

Currently I have to do this in 3 lines:

```
A.sort()
B.sort()
A.should.eql(B)
```

Since this is a common scenario, it could be very useful to do this in 1 line, for example:

```
A.sorted.should.eql(B.sorted)
```

... or something like this.

**Comment by btd** [comment]
I do not think it is common case and that should.js should do everything that can be tested.
