### ISSUE TITLE
How are Git submodules related to using Should?

### ISSUE THREAD

**Issue by rm-rf-etc** [tj/should.js#135]
The readme states:
Running tests
To run the tests for should simply update your git submodules and run:
$ make test

I have not used git submodules, but based on my search results, I see no relation between them and should.js. If I'm using mocha, wouldn't I just execute $ mocha ? Why does the readme specify to run make?

**Comment by btd** [comment]
In should.js there is nothing about submodules now. Previously maiby 2 years ago it used submodule to load test runner, now it is gone.
`make test` need to run own tests for should.js, you do not need this if you are not contributing.
