### ISSUE TITLE
idea: of

### ISSUE THREAD

**Issue by ianstormtaylor** [tj/should.js#141]
i think the grammatically correct way to test `typeof` would be:

```
.should.be.of.type('string')
```

instead of:

```
.should.have.type('string')
```

just tripped me up a second ago

**Comment by ianstormtaylor** [comment]
slash i thought i could just do this:

```
.should.be.a('string')
```

but this isn't the case?

**Comment by btd** [comment]
Hey, i agree about `.of`. 
We make `.a` to be an alias for `.an` in `2.x.x`. Now to get type use `.type`.
