### ISSUE TITLE
npm install should doesn't include /lib/should.js

### ISSUE THREAD

**Issue by bkimmel** [tj/should.js#142]
Not sure if this is just specific to my machine, but I just ran an "npm install should --save-dev" per the readme... it brought eql.js, http.js and util.js into node_modules/should/lib directory but not should.js.  Got it working by just copying and pasting raw from should.js .. probably some local problem (machine is Windows 7 professional SP1), just thought I'd pop a notice in case.  Love the library - keep up the good work.

**Comment by btd** [comment]
There was a problem, when we by mistake have added `should.js` file pattern to `.npmignore`. It should be fixed already. You need to check that you do not use 2.0.0, but at least 2.0.1.
