### ISSUE TITLE
Problem comparing object to array

### ISSUE THREAD

**Issue by ARAtlas** [tj/should.js#148]
I would expect the following unit test to pass:

```
var obj = { '0': 'hello' };
var array = ['hello'];

obj.should.be.instanceOf(Object);
array.should.be.instanceOf(Array);

obj.should.not.eql(array);
```

However, it fails with:

```
AssertionError: expected { '0': 'hello' } to not equal [ 'hello' ]
```

**Comment by btd** [comment]
In your case it is equal because enumerable properties are the same:

```
> Object.keys(obj)
[ '0' ]
> Object.keys(array)
[ '0' ]
> 
```

`.eql` not strictly equal (as i know there is no right way to know that 2 objects was produced with the same constructor function) and you need to combine this with other checks.

**Comment by L8D** [comment]
Would there be a sane way of checking whether they're both instances of or
both not instances of array?

**Comment by L8D** [comment]
Perhaps a check like: `obj1 instanceof Array === obj2 instanceof Array`

**Comment by btd** [comment]
As i know one way it is using `.constructor`:

```
$ node
> var a = [];
undefined
> var b = {};
undefined
> a.constructor
[Function: Array]
> b.constructor
[Function: Object]
> 
```

But this is only convention and not an standard.

**Comment by ghost** [comment]
Wait, .constructor is convention? Are you sure about this? The V8 and TraceMonkey runtimes seem to behave this way.

**Comment by btd** [comment]
ecma-262 said about `.constructor` only in native objects. Correct me if i am wrong (i would like to be wrong there).
Node team do not use it in [assert module](https://github.com/joyent/node/blob/master/lib/assert.js#L197) (they maybe better know then I).
I know that ff and chrome add this in Object.create, but still as i said it is not a standard thing.

``` js
$ node
> function Test() {}
undefined
> (new Test).constructor
[Function: Test]
> 

```

**Comment by L8D** [comment]
Yeah, comparing .constructor can potentially cause issues if there is a
class which extends `Object`somehow.

**Comment by btd** [comment]
I will close this, as we all know dynamic types nature of js do not allow us to check that references have the same time and user is responsible to check types (as usually he knows types better than abstract library) before comparing object of different types.
If will be any good enough way to check this i will add it.
