### ISSUE TITLE
should.not.be.json doesn't work

### ISSUE THREAD

**Issue by andrezsanchez** [tj/should.js#158]
Using `whatever.should.not.be.json` behaves the same as `whatever.should.be.json`

**Comment by alsotang** [comment]
Could you please give a fail example??

This is the implement of .should.be.json :+1: 

``` js
  get json() {
    this.obj.should.have.property('headers');
    this.obj.headers.should.have.property('content-type');
    this.obj.headers['content-type'].should.include('application/json');
    return this;
  },
```

I think .should.not.be.json will work if the Object is not a json.

---

SORRY, I'm wrong..It really doesnt work.

**Comment by andrezsanchez** [comment]
Eh, maybe I should have thought about this more (and gone to sleep).  I'm not sure should.not.be.json would have any use anyways, can't remember what I was trying to do when I found this.  I would close this and #159, but I suppose @visionmedia might care, otherwise go ahead and close them.

**Comment by alsotang** [comment]
Should.js is now maintained by @btd

**Comment by btd** [comment]
Fixed in master
