### ISSUE TITLE
Use `Proxy` if available to detect false positives

### ISSUE THREAD

**Issue by lydell** [tj/should.js#161]
``` js
foo.should.be.empty
bar.should.be.a.string // oops! Possible false positive that can slip through.
```

By wrapping the return value of the [`should` function](https://github.com/visionmedia/should.js/blob/7805a508828e93d2bd9a710c939fa96932c577e2/lib/should.js#L24) in a `Proxy` such errors could be caught.

Something like this:

``` js
function proxy(obj) {
  if (typeof Proxy === "function") {
    return new Proxy(obj, {
      get: function(target, prop) {
        if (prop in obj) {
          return target[prop]
        } else {
          throw new Error("No such thang")
        }
      }
    })
  } else {
    return obj
  }
}
```

**Comment by alsotang** [comment]
Good suggestion. But seems proxy in ES5 is not such simple? As I know, in ES5 it's not easy to catch a undefined property of a certain object.

**Comment by lydell** [comment]
`Proxy` is an ES6 feature. There is nothing we can do in ES5. The idea of the `proxy` function is to only use a `Proxy` if available. Otherwise there should be no difference.

**Comment by btd** [comment]
Move discussion to https://github.com/shouldjs/should.js/issues/35
