### ISSUE TITLE
should.throw(): How pass argument to functions?

### ISSUE THREAD

**Issue by diosney** [tj/should.js#163]
Hi,

How can I pass arguments to the functions that will be tested with `should.throw()`?

For instance, I have the following function:

```
 var func = function(flag){
         if (flag) {
         throw new Error('fail');
         }
 };
```

What I need is to do is something like:

``` js
func(true).should.throw();
func(false).should.not.throw();
```

**Comment by diosney** [comment]
I already tested with:

```
    should(func(true)).throw();
```

But when the test is run then the Error stack is show rather than captured by `should`

**Comment by btd** [comment]
Maybe, just:

```
func.bind(null, true).should.throw();//?
```

**Comment by diosney** [comment]
Worked like a charm, thanks!

Can you consider adding this example to the docs?

**Comment by diosney** [comment]
I know its straightforward, but just in case :)

**Comment by btd** [comment]
Yes, no problem, i will reopen this to do not forget.

**Comment by alsotang** [comment]
How to pass arguments to `setTimeout`/`process.nextTick` and so on?

just 

``` js
(function () {
  func(true);
}).should.throw();
```

is ok.

**Comment by btd** [comment]
Fixed in master.
