### ISSUE TITLE
Travis can't import should

### ISSUE THREAD

**Issue by AdrienLemaire** [tj/should.js#165]
Hello,

I can't resolve an issue `Error: Cannot find module 'should'` (cf [this travis build](https://travis-ci.org/CoinsManager/CoinsManager/builds/16838956) )

my [.travis.yml](https://github.com/Fandekasp/CoinsManager/blob/a1db65590877247b96c0e0298eb935191f79c7f0/.travis.yml) does install should, so it's a mystery why the tests fail (I don't have any problem loading should in my local machine).

Do you have any idea ?

**Comment by AdrienLemaire** [comment]
I tried to add a `npm link should`, but then I get a [Require is not defined](https://travis-ci.org/CoinsManager/CoinsManager/builds/16839626) error, very strange

**Comment by alsotang** [comment]
There is only `npm install -g should` in your .travis.yml. But your project folder doesn't know you have `should` installed. Please just `npm install should` in your project folder.

And this problem is not related to `should`. It is mostly a test or deploy problem of Meteor.

**Comment by AdrienLemaire** [comment]
ok thanks. I'm getting other errors now, this is a problem related with travis. Sorry for the disturb :)
