### ISSUE TITLE
.which does not chain after property assertion

### ISSUE THREAD

**Issue by basicallydan** [tj/should.js#166]
The chain item `.which`, as far as I can tell, should allow chained assertions like the following:

`book.should.have.property('title').which.should.eql('Intro to Unit Testing');`

However, at this point `.which` is `undefined`. In order to make this particular type of chained assertion work I need to do the following.

`book.should.have.property('title').which.should.eql('Intro to Unit Testing');`

This feels like a hack to me. Is all of the above expected?

**Comment by btd** [comment]
Yes `.which` is missing now, because it is only in master. I will publish soon it as we discuss all edges of new version.

**Comment by basicallydan** [comment]
Oh, great! Cool :) thanks @btd
