### ISSUE TITLE
confusion with optional arguments

### ISSUE THREAD

**Issue by mcranston18** [tj/should.js#168]
I'm trying to enact the optional error description but am having trouble. I'm using Mocha and trying to execute the following:

<pre>
describe('a test ', function() {
    it('will perform a test', function() {
        var num1 = 1;
        var num2 = 2;
        num1.should.eql(num2, 'or the test will fail and this error should be appear');
    });
})
</pre>

The test will fail as expected, but I won't see the the error message.

**Comment by btd** [comment]
Actually bug in mocha. With this [PR](https://github.com/visionmedia/mocha/commit/34116d5), which was done only for chaijs, ruin partially other libraries.
If we [see there](https://github.com/visionmedia/mocha/commit/34116d5#diff-5c8a5788ecd4b4af2a29bc27ac4ae986R186) mocha begin expect message in format: contex:message. Which should.js does not use of course and weird thing that it just reject all other formats with `match ? ... : ''`.

@travisjeffery correct me if i am wrong, but it really looks like mocha bug. Easy fix to replace [line 191](https://github.com/visionmedia/mocha/blob/be674a20a7feba36a6b62d5f6d96e7c30c9cadde/lib/reporters/base.js#L191) from:

```
msg = match ? '\n      ' + color('error message', match[1]) : '';
```

to:

```
msg = '\n      ' + color('error message', match ? match[1]: msg);
```

Result before:
![2014-01-18 15 28 01](https://f.cloud.github.com/assets/334851/1946961/a1cf94a2-8033-11e3-8c5a-8627f5ce09f5.png)

and result after:
![2014-01-18 15 28 52](https://f.cloud.github.com/assets/334851/1946965/dc9001f8-8033-11e3-86bc-4bb0e120acfd.png)

**Comment by btd** [comment]
@travisjeffery Thanks.

**Comment by travisjeffery** [comment]
:+1:
