### ISSUE TITLE
require("should").eql == null => true

### ISSUE THREAD

**Issue by weepy** [tj/should.js#17]
fresh install

npm install should

node

> require("should").eql == null
> true

what is happening ?

**Comment by lackac** [comment]
@weepy, the exported object from should is not the same as you get when accessing the property with the same name on any object. Only the `exist` property and some modifiers are available on it. See the section titled "exist (static)" in the [README](/visionmedia/should#readme). That said, it seems that _should_ doesn't work well in REPL.

Try running the following code with node and it may clarify it more:

``` javascript
var should = require("should");
console.log("should.eql", typeof should.eql);
console.log("should.exist", typeof should.exist);                        
console.log("'foo'.should.eql", typeof "foo".should.eql);
```

It will print the following:

```
should.eql undefined
should.exist function
'foo'.should.eql function
```
