### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by shortstuffsushi** [tj/should.js#172]
Hey there,

I noticed at the bottom of your readme, you've listed your project as being under the MIT license, but unlike Mocha, you haven't actually included a copy of the license. Want to do so?

**Comment by btd** [comment]
Nope, MIT does not require to include license text (as ASF e.g.). But maybe makes sense to add url for text.

**Comment by shortstuffsushi** [comment]
Fair enough, I just thought that was kind of the 'standard practice' for these libraries. You're right that it's not required, though.

**Comment by btd** [comment]
Nope as i know it is not standard practice for lawyer department always better to include such thing, but i am not a lawyer and do not care - if somebody will add in PR license text i will merge it.
So while noone really care about it, i do not care too. As someone will need to show license i will add it.
