### ISSUE TITLE
Browser: assert is undefined

### ISSUE THREAD

**Issue by jgillich** [tj/should.js#185]
I'm not sure if I am missing something, but it seems like the  `assert` module does not work (anymore?):

```
console.log(typeof {}.should);
// "object"
console.log(typeof assert);
// "undefined"
```

Using the `should.js` from the root. Fiddle: http://jsfiddle.net/Nbqq7/

**Comment by travisjeffery** [comment]
the assert module in node isn't available in the browser, you need something like chai's assert: http://chaijs.com/api/assert/

**Comment by jgillich** [comment]
The README actually states should.js can be a replacement for node's assert module (or I am just misunderstanding it). Anyway, thanks for the quick response!

**Comment by travisjeffery** [comment]
ya look at the code example below that

on each line there's an example of using assert and to the right using should.js

**Comment by jgillich** [comment]
Oh now I feel really stupid. Thanks again, I think I need some sleep :smile:
