### ISSUE TITLE
'not' in combination with 'properties' is asserting incorrectly

### ISSUE THREAD

**Issue by kentaf** [tj/should.js#192]
The call(-chain) to `should.not.have.properties()` asserts to true if any of the given properties is not given although another one that should not be present actually is.

```
o={a: 1};
o.should.not.have.properties(['a', 'b']) // asserts to true
```

Expected outcome: the assertion should fail when one of the properties listed in the properties method is present in the object being asserted.

Tested with v3.1.2

**Comment by btd** [comment]
Yep, agree this makes sense.

**Comment by cjroth** [comment]
Just encountered this bug as well.

+1.

**Comment by kentaf** [comment]
After trying to create a 'fix' for this issue, I realized that this is more a bug with the English language being sloppy rather than being a bug with should.js. I would like to request to un-label this as a bug and propose a feature request instead. Here the reasoning:

If we say `myObj.should.have.properties('a','b')`, we really mean that myObj should have **all** properties, namely `a` **and** `b`. When using a negation with the `not` property, should.js just inverts the assertion, so `myObj.should.not.have.properties('a','b')` really means that myObj should not have `a` **and** should not have `b` - this is working properly. Hence, having just `a` and not `b` asserts to true.
The confusion arises that when we, as English speaking people, read the above negated assertion, we implicitly think of something like `.should.not.have.anyOfTheFollowing.properties(...)`.

I would like to propose a method along the lines of `containAny(arg1, arg2, ..)` and `containAny([args])` that asserts to true if _any_ of the given arguments is present in the asserted object. Negating this method would accomplish what started this thread. I would be happy to create a pull request, if we agree upon the details.

**Comment by cjroth** [comment]
I agree with @kentaf.

**Comment by btd** [comment]
In branch `any` i added `.any` modifier that should work as you expected. I published it in npm to 3.2.0-beta1 and this modifier affect only for .properties now.

To show what it do i copy test:

``` js
'test'.should.have.any.of.properties('length', 'a', 'b');

    'test'.should.have.any.of.properties('length');

    ({ a: 10 }).should.have.any.of.properties('a', 'b');

    ({ a: 10 }).should.have.any.of.properties({ a: 10, b: 12 });

    ({ a: 10 }).should.not.have.any.of.properties('b', 'c');

    ({ a: 10 }).should.have.any.of.properties(['a', 'b']);

    err(function() {
      ({ a: 10 }).should.not.have.any.of.properties(['a', 'b']);
    }, "expected { a: 10 } not to have property 'a'");

    err(function() {
      ({ a: 10, b: 10 }).should.not.have.any.of.properties(['a', 'b']);
    }, "expected { a: 10, b: 10 } not to have any of properties 'a', 'b'");

    err(function() {
      ({ a: 10, b: 10 }).should.not.have.any.of.properties({ a: 10, b: 12 });
    }, "expected { a: 10, b: 10 } not to have property 'a' of 10");

    err(function() {
      ({ a: 10, b: 10 }).should.not.have.any.of.properties({ a: 10, b: 10 });
    }, "expected { a: 10, b: 10 } not to have any of properties 'a' of 10, 'b' of 10");

    err(function() {
      ({ a: 11, b: 11 }).should.have.any.of.properties({ a: 10, b: 10 });
    }, "expected { a: 11, b: 11 } to have any of properties 'a' of 10 (got 11), 'b' of 10 (got 11)");
```

I appreciate feedback on this version (names, messages, typos, logic etc), i will continue add it to `.keys` first and maybe `.contain*` methods.

**Comment by kentaf** [comment]
I think this is great! Using a modifier that can be applied to `properties`, `keys` and `contain*` makes it flexible. Here some very minor thoughts:
- reading the assertion, it makes you wish for a `the` chaining modifier: `should.have.any.of.the.properties` :)
- the variable name `this.one` tripped me for a bit ...

Thank you for the quick implementation

**Comment by btd** [comment]
Adding chaining getters is not a problem, so i will add `.the`.
Do you have a better name for `this.one`? (i agree that it is confusing)

**Comment by kentaf** [comment]
How about `this.anyOne` ?

**Comment by btd** [comment]
Looks good.

**Comment by glebkhol** [comment]
This one got me by surprise. Should <code>not.have.properties([more than 1])</code> be disallowed to keep people from making accidental mistakes? Test infra should be especially robust against accidental misuse.

**Comment by btd** [comment]
Well, looking on other assertions .any modifiler does not make any sense for them.
