### ISSUE TITLE
Does it make sense for "throws()" to handle an object exception

### ISSUE THREAD

**Issue by awol** [tj/should.js#193]
Hi,
Exceptions within our project throw objects with a "name" attribute describing the category of the exception and a "message" attribute containing the exception message (perhaps even some other features in these objects at a future date).

Does it make sense to have a case within the "Assertion.add('throw'" definition to handle the case when an object is thrown by allowing attribute comparison in the assertion definition within the test case?

**Comment by btd** [comment]
I think yes, it can be usefull - it is not rare when error objects has a lot of custom fields. From what i would like to see: first it is as you said compare properties and the second thing it is quite useful in the same time check constructor function.
Also i think no need to touch 'throw' as it only limit to do not change signature (to do not break anything). Maybe better to take another name and use similar way used in `.match`, makes sense?

**Comment by btd** [comment]
It should be in master
