### ISSUE TITLE
Crash when used with request

### ISSUE THREAD

**Issue by alexwhitman** [tj/should.js#196]
Using should 3.1.4, request 2.34.0 with node 0.10.26 causes a script to crash simply by being required.

This works fine:

``` js
var request = require('request');

request.get('http://www.google.co.uk', function(error, response, body) {

    console.log(response.headers);

});
```

This fails with an "Unhandled 'error' event":

``` js
var request = require('request');
var should  = request('should');

request.get('http://www.google.co.uk', function(error, response, body) {

    console.log(response.headers);

});
```

The only change is the inclusion of the should require.  Not sure if it's request or should at fault.

**Comment by btd** [comment]
Just noticed. Second line 

```
var should  = request('should');
```

Actually need to replace request to require. And everything works fine =).

**Comment by alexwhitman** [comment]
Oops, not sure how I missed that. Sorry for the noise. :)
