### ISSUE TITLE
how to test for truthiness ?

### ISSUE THREAD

**Issue by weepy** [tj/should.js#2]
not sure how to do this ? 

getValue().should.be.ok ?

**Comment by tj** [comment]
value.should.be.true

**Comment by weepy** [comment]
that's not right.

truthy means value that would be coerced to true. E.g. if(2) ...

**Comment by tj** [comment]
ah sorry, I see what you want now. I would use the non-strict equality `foo.should.eql(true)` but we could add `ok`

**Comment by weepy** [comment]
ah - well the docs are a little confusing --- .eql looks like deepEqual --- but i suppose it does non-strict equality too. should.be.ok would be decent though.

**Comment by tj** [comment]
k, I added it

**Comment by weepy** [comment]
:D:D:D:D:D

**Comment by tj** [comment]
yup .eql is deepEqual, because deepEqual is a brutal name lol the assert module just flat-out sucks
