### ISSUE TITLE
Typo in the README

### ISSUE THREAD

**Issue by samyakbhuta** [tj/should.js#20]
The 'bar' has been replaced by 'baz' and vice versa.

In sectiion: Assert own object keys, which must match exactly, and will fail if you omit a key or two:

obj.should.have.keys('foo', 'bar'); should be obj.should.have.keys('foo', 'baz')
obj.should.have.keys(['foo', 'bar']); should be obj.should.have.keys(['foo', 'baz']);
obj.should.include.keys('bar'); should be obj.should.include.keys('baz');
obj.should.not.include.keys('baz'); should be  obj.should.not.include.keys('bar');

**Comment by shinuza** [comment]
This has been changed, this issue is now invalid.

**Comment by shuny** [comment]
In that case you can close the issue.
