### ISSUE TITLE
should.null, should.false, should.true, should.instanceof breakes parser on webkit browser

### ISSUE THREAD

**Issue by klammbueddel** [tj/should.js#201]
Dear community,
we use should as assertion framework on a vendor customized webkit browser. Everything works as it should expect that the .null assertion will break the javascript parsing. Their is no console available so I cannot give you an error message.

The parser will just stop when .null is used anywhere in the code:

```
alert("You won't see me.")
function test(){
    var item = {};
    item.should.not.be.null;
}
```

Since this pattern is used in lib/ext/property.js in line 207 

```
should(item).not.be.null.and.containDeep(other[otherIdx]);
```

and line 226

```
should(obj[key]).not.be.null.and.containDeep(value);
```

this breakes our test suite.

Using null as a property might be not a good idea at all, since some browsers might not like that. As said, this is the only issue that breakes should on the browser we have to use.

**Comment by klammbueddel** [comment]
update:

```
true.should.be.true
```

and 

```
false.should.be.false
```

have the same issue and should be avoided

**Comment by btd** [comment]
Hi.

Interesting issue, it looks your js engine does not support any js keywords as properties. Even ie9 support it - because it is one of the features of es5.
I can fix it, but i pretty sure your engine will fail on something else not supporting es5 fully. If you want you can make PR with this, but i will not work on this, as i am sure that is not only issue with your custom engine.

**Comment by klammbueddel** [comment]
Yes, its weired. Same issue with instanceof
But:

```
true.should.be.True;
false.should.be.False;
Should(null).should.be.Null;
x.should.be.instanceOf(X);
```

will work just fine.
I added a PR #202 to fix it. I did not found any occurences of .true, .false, .null and .instanceof into the repo. Please take care that nobody will ever use them ;)

**Comment by btd** [comment]
I added aliases for `.true`, `.false`, `.null`. Try 3.3.1

**Comment by klammbueddel** [comment]
Since 3.3.\* `Should(null).should.be.Null` fails.
You said you have also added an alias for `.null`, can you double check this please.
`Should(null).equal(null)` works but `Should(null).should.be.Null` and `Should(null).should.be.null` both fail with `expected { obj: null } to be null`

Regarding the documentation .null and .Null are both not supported, but still used in property.js.
What is your opinion, should it be or is it already part of the spec?

**Comment by btd** [comment]
Well.
`Should(null).should.be.null` is not the same  as `Should(null).be.null`. Should(something) working like something.should it is exactly the same.

**Comment by klammbueddel** [comment]
That completely makes sense. I fixed my tests and they work like a charm. Thank you for the help!
(I think the documentation still needs an update.)

**Comment by btd** [comment]
Could you pls, check if .arguments give the same result?

**Comment by klammbueddel** [comment]
`.arguments` work just fine

**Comment by btd** [comment]
Thanks, wanted to be sure.
