### ISSUE TITLE
.containDeep() depends on item order

### ISSUE THREAD

**Issue by lobodpav** [tj/should.js#203]
These asserts work well:
- [1, 2, 3].should.containDeep([1, 2]);
- [1, 2, 3].should.containDeep([1, 3]);

However, changing order of items causes the assert to fail:
- [1, 2, 3].should.containDeep([3, 2]);

I would expect that the order of items in `.containDeep()` argument does not matter because I want to check if the checked array contains all items in the argument no matter the order.

**Comment by btd** [comment]
I agree and don't agree in the same time.
I assume that array is ordered collection and that is why it check order in which elements presented. In opposite object goes unordered.

**Comment by lobodpav** [comment]
Good point. Could you mention that in the doc?

I solved this by

``` js
var arrayToCheck = [1, 2, 3];
[3, 2].forEach(function(item) {
    arrayToCheck.should.containDeep([item]);
});
```

but I thought it would be nice if I would not have to write so much boilerplate everywhere in my tests.

**Comment by btd** [comment]
Agree, about i can add methods like .containEql and .containDeep that just check existence. Any suggestion about name? (it seems switch for method will be not enough, also i am worry how to make it less confusing)

**Comment by lobodpav** [comment]
Yeah, was thinking about a good name too. First I thought I would rename the existing ones to `.containEqlOrdered` and `.containDeepOrdered`. But hard to say how many people adopted these already.

**Comment by yoshuawuyts** [comment]
I think `.containEqlOrdered()` and `.containDeepOrdered()` make the most sense. If you're looking to check something in a certain order, most of the time you'll do a `.equal()` anyway.

**Comment by btd** [comment]
I will close this as it already in master (will publish today or at weekend). If you have issues about it, pls create new one in [shouldjs/should.js](https://github.com/shouldjs/should.js).
