### ISSUE TITLE
Would make sense for should.have.keys() to cast integer arguments to strings before comparing

### ISSUE THREAD

**Issue by DanielSmedegaardBuus** [tj/should.js#208]
Hi :)

Since keys on an object have to be strings, IMHO I think it might make sense for should to cast integers before trying to compare. As it stands now, it gives AssertionError if you don't cast them yourself. E.g., I have to do:

```
game.statuses.should.be.an.Object.and.have.keys(''+match1.id, ''+match3._id);
```

to not get

```
Uncaught AssertionError: expected { '1': 'cancelled', '3': 'deleted' } to have keys 1, 3
    extra keys: '1', '3'
```

**Comment by btd** [comment]
Yep, i will add it.

**Comment by DanielSmedegaardBuus** [comment]
Cool, thanks! :)

**Comment by btd** [comment]
I will close this as it already in master (will publish today or at weekend). If you have issues about it, pls create new one in [shouldjs/should.js](https://github.com/shouldjs/should.js).
