### ISSUE TITLE
Uncaught TypeError: Object #<Assertion> has no method 'status'

### ISSUE THREAD

**Issue by joan-i** [tj/should.js#209]
I started seeing above error with existing mocha test.  This used to work:
var callback = function (err, result) {
                result.should.have.status(200);
}

Any idea why it stopped working? Should module which gets pulled in is version 4.0.0

**Comment by btd** [comment]
You need to install also `should-http`. In 4.x i moved all non core staff in own repos.

**Comment by btd** [comment]
Also use new repo location to create issues, i will close this one, if you have issues open in new repo.
