### ISSUE TITLE
Bump version number so object includes are in NPM

### ISSUE THREAD

**Issue by edmellum** [tj/should.js#21]
The new object include assertion is awesome, but I can't use it with my NPM version of Should. Could you please bump the version number so I can get it without git clone?

**Comment by tj** [comment]
hmm nothing appears to have changed since 0.2.1

**Comment by edmellum** [comment]
If you check out the commit log it looks like you merged a pull request an hour after having released 0.2.1. That pull request was what implemented object includes.

**Comment by tj** [comment]
my bad, I didn't pull from github
