### ISSUE TITLE
fork vs move

### ISSUE THREAD

**Issue by notslang** [tj/should.js#210]
Github now supports [repository redirects](https://github.com/blog/1508-repository-redirects-are-here), so rather than forking should.js into its new home at shouldjs/should.js, you can transfer the repository and it will carry all of its issues, stars, and watchers with it. But most importantly, everything will automatically redirect to the new org.

I used this when migrating https://github.com/wp-sync-db/wp-sync-db, and I can confirm that it all works flawlessly. Even when combined with renaming the repo.

**Comment by btd** [comment]
Yep, i know about it, but i have no admin rights on that repo. If @visionmedia can assist in this. That could be great.

**Comment by tj** [comment]
I don't really see a reason for it to have its own org really, it's pretty stand-alone

**Comment by btd** [comment]
There was several reasons for this. First of all i do not have full access to this repo, i could not setup travis account, install sauce labs etc. Now i did this, split library (as now it used not only for node - also browser, alloy titanium etc). 
For all these things i think better to split library and move to organization ( i do not see any reason to have that repo in my account, as i only help you maintain it ).

**Comment by notslang** [comment]
So, we should either have @visionmedia deal with setting up all the travis/sauce labs stuff on this repo. Or, have @visionmedia transfer the repo to an organization for the purpose of having more granular control over user permissions. Thoughts?

**Comment by yanickrochon** [comment]
Community projects should have their own repo/org once they reach a certain growth and popularity. This will just make development easier. Especially when most recent commits are done by contributors. This is my opinion.

**Comment by tj** [comment]
yea transfer would be better, I still feel like it's pretty stand-alone. full-access contributors can't change hooks etc? that's weird

**Comment by gaastonsr** [comment]
This should be moved for respect to the new maintainers. And from the users point of view is annoying to enter this repo to later be redirected to the new one. Given this is the first repo that appears when somebody searches "shouldjs" in google.

**Comment by tj** [comment]
my point is it does not need its own org at all, some larger projects make sense as orgs, this one does not, IMO we should just keep it here where people are used to seeing it, I can enable travis or whatever else, I just didn't realize GH does not allow contributors to add hooks
