### ISSUE TITLE
Too generic error message in custom assertion

### ISSUE THREAD

**Issue by PandaWhisperer** [tj/should.js#214]
I am trying to custom assertions so I can easily test whether a given JavaScript object conform to one of my domain models. I'm using the following code:

``` javascript
should.use(function(should, Assertion) {

  // checks if a given object is an Asset
  // this lets us write e.g. `obj.should.be.an.Asset`
  Assertion.add('Asset', function() {
    this.params = { operator: 'to be an asset' };
    var asset = this.obj;

    should(asset).be.an.Object;
    asset.should.have.property('asset_id');
    // ... other assertions
  }, true);
});
```

This works, as in, `obj.should.be.an.Asset` fails if `obj` does not pass all of the assertions. However, the error message that is returned is always just `expected [Object] to be an asset`. I would prefer the message to also contain the _specific reason_ (i.e. the exact assertion that failed), such as a missing property.

How can I achieve this?

**Comment by btd** [comment]
Currently there is no anything internal for this. But definitely worth to add.
Like adding tab for nested assertion. What do you think?

PS. There is new repo for shouldjs.

**Comment by PandaWhisperer** [comment]
Thanks for the update and apologies for posting on the old repo. Looks like the new additions to the README explain the correct process to add custom assertion. I'll study those and get back to you on the current repo.
