### ISSUE TITLE
Please remove the registry of bower

### ISSUE THREAD

**Issue by qqzh002** [tj/should.js#215]
Hi,

Since this repo is not maintained anymore, please remove the registry from bower. So that the new repo can be registered with the name "should".

Thanks

**Comment by btd** [comment]
There is neither [should](http://bower.io/search/?q=should) nor [should.js](http://bower.io/search/?q=should.js) in bower registry. Could you explain what you mean?

**Comment by qqzh002** [comment]
If you run `bower search should` you will get the following result:

![screen shot 2014-11-09 at 9 58 38 am](https://cloud.githubusercontent.com/assets/3662141/4966231/329cefd4-67b5-11e4-95af-9b03660bc646.png)

I guess maybe someone else register this repo on bower, but only the owner can remove this from bower.

About how to unregister, please refer to: http://bower.io/docs/creating-packages/#unregister

**Comment by btd** [comment]
Fixed now

**Comment by qqzh002** [comment]
Thx
