### ISSUE TITLE
.exist() for syntactic consistency

### ISSUE THREAD

**Issue by jtmarmon** [tj/should.js#216]
should.js encourages english-like assertions so that they're very easy to read.

i.e.

`response.should.have.header('content-length')`

`obj.should.have.keys('foo', 'baz');`

And so on.  However, to assert that a variable "exists" (which is often more clear or practical than asserting ...`.should.not.equal(undefined)`) you must break the english-like pattern by writing
`should.exist(obj);`  There should be a way to write it like so: `obj.should.exist()`

**Comment by jtmarmon** [comment]
A friend of mine has pointed out that `undeclaredVariable.should.exist()` wouldn't exactly work ;) forgive me

**Comment by btd** [comment]
That is usually `should.exist(abc)` or `should(abc).be.ok`
