### ISSUE TITLE
greater equal always fails

### ISSUE THREAD

**Issue by AngelKyriako** [tj/should.js#217]
All related methods like those below fail for me:

```
should(1 >= 0).be.ok;
(1).should.be.GreaterEqual(0);
```

I am using sails 0.10.5 with mocha:

```
"devDependencies": {
    "barrels": "^1.3.0",
    "mocha": "^2.0.1",
    "sails-memory": "^0.10.3",
    "should": "^4.3.1",
    "supertest": "^0.15.0"
  }
```

Maybe I am missing the proper method, in that case sorry to bother u

**Comment by btd** [comment]
There is no method `.GreaterEqual`, there is [`.above`](https://github.com/tj/should.js#abovenum-and-greaterthannum).
Also read first  line of readme.
