### ISSUE TITLE
How to assert if string is lexicographical after/before ?

### ISSUE THREAD

**Issue by hotaru355** [tj/should.js#219]
Is there a smarter (more verbose) way of asserting

```
should.ok("zzz" > "aaa")
```

or is there a way to register own assertion methods?

Thanks.

**Comment by btd** [comment]
Hi.
First of all take a look on first line of readme (repo was moved).
yes you can add own assertions:

```
var should = require('should');

should.Assertion.add('method', function(val) {
this.params = { operator: 'to be lexicographically less', expected: val };

this.assert(this.obj > val);
});

'zzz'.should.method('aaa');
```

If you need more help recreate issue in correct repo.
