### ISSUE TITLE
('hui').should.be.a.Number;  - passing test

### ISSUE THREAD

**Issue by romanesko** [tj/should.js#222]
What I do wrong?

**Comment by btd** [comment]
You are doing a lot of things wrong:
1. You are writing to wrong repo (aka read README.md).
2. You do not specify which version of should.js you are using (aka read CONTRIBUTING.md).
3. In 7.x all getter assertions are removed to be function .Number() (see item 1);
4. I hope `hui` it is just word and you do not mean any bad words. Next time i will lock such issues, and will close without any answering.

**Comment by romanesko** [comment]
I haven't seen any restrictions to the use of words in the tests in the README.md
Thank you.
