### ISSUE TITLE
true.should.be.false is passing

### ISSUE THREAD

**Issue by ghost** [tj/should.js#223]
What am I doing wrong?  I'm trying to to test out should with mocha and I am having some issues.  I have a test file, test/test.js where I am trying to get one pass and one fail, but both tests always fail:

``` javascript
'use strict';

describe('Test', function () {
  it('should succeed', function () {
    true.should.be.true;
  });

  it('should fail', function () {
    true.should.be.false;
  });
});
```

> mocha ./test --require should || true

  Test
    ✓ should succeed
    ✓ should fail

  2 passing (7ms)

I'm using mocha 2.3.3 with should 7.1.0 on node 0.12.2.

**Comment by btd** [comment]
`.true()`
`.false()`

also it is not right repo.
