### ISSUE TITLE
Why {false.should.be.ok} can pass test

### ISSUE THREAD

**Issue by sunkuo** [tj/should.js#225]
Hey , Sir , i use mocha and should to test my library , whatever, i found  {false.should.be.ok } can pass the test . WHY?

**Comment by sunkuo** [comment]
Here is the code  
![screen shot 2016-05-27 at 4 39 45 pm](https://cloud.githubusercontent.com/assets/5069192/15602758/ab95c604-2429-11e6-9770-f0335abe862e.png)

Here is the result:
<img width="539" alt="screen shot 2016-05-27 at 4 40 25 pm" src="https://cloud.githubusercontent.com/assets/5069192/15602772/bdc7900a-2429-11e6-8227-f0da8ac7cf77.png">

**Comment by sunkuo** [comment]
it really confused me

**Comment by richardlay** [comment]
@sunkuo how did you fix this?
