### ISSUE TITLE
should.not.exist and should.exist are not working

### ISSUE THREAD

**Issue by c4milo** [tj/should.js#25]
I'm getting this error 
TypeError: Object #<Object> has no method 'exist'

when using 
 should.not.exist(key) or should.exist(key)

I'd expect it to work as documented in https://github.com/visionmedia/should.js/blob/master/Readme.md

Let me know if this issue should be reported in should.js instead.

**Comment by marlun** [comment]
Using Mocha 1.0 I'm getting the exact same error:

TypeError: Object # has no method 'exist'

I'm running mocha like this: mocha --require should test/*/.js

If I however add "var should = require('should')" in the code then everything works but the docs of mocha specifically tells you that you can use "--require should" instead?

**Comment by toberndo** [comment]
@marlun I once opened the following issue for this on Mocha:
https://github.com/visionmedia/mocha/issues/257

The explanation is: 'mocha --require should' only extends Object.
Then you can write things like:

obj_xyz.should.equal(0);

But it does not expose a global variable 'should'.
Therefore the following will not work:

should.exist(obj_xyz);

It is then required to add "var should = require('should')"

Probably a hint in the docs would be good.

**Comment by marlun** [comment]
That explains it, thanks!

**Comment by vincentmac** [comment]
Just a heads up, this issue is documented on the [Mocha Page ](http://visionmedia.github.com/mocha/).

_Section: **mocha(1)**_
**-r, --require <name>**
_The --require option is useful for libraries such as should.js, so you may simply --require should instead of manually invoking require('should') within each test file. Note that this works well for should as it augments Object.prototype, however if you wish to access a module’s exports you will have to require them, for example **var should = require('should')**._

**Comment by c4milo** [comment]
Thanks for the heads up!

**Comment by fabriziomoscon** [comment]
Workaround:
https://github.com/fabriziomoscon/coffeestack/blob/c30855d0426dfb86ca489f888c274c9fa4a78e03/test/init.js

**Comment by andrewjmead** [comment]
I'm using mocha and should.js in the browser. Everything seems to work, but I'm getting:

```
TypeError: Object #<Object> has no method 'exist'
```

when running something like

```
should.exist(app);
```

---

I can't find any specifics on how to make this work.

I understand that I could use `app.should.exist()`, but then the errors shown in the spec runner become less useful.

**Comment by btd** [comment]
@andrewjmead Pls open another issue. This one about making mocha and should.js working together.

**Comment by andrewjmead** [comment]
For reference, I created an issue in the mocha repo: https://github.com/visionmedia/mocha/issues/1075

**Comment by webjay** [comment]
works for me if I `require('should');`
