### ISSUE TITLE
should.be.null and should.be.undefined?

### ISSUE THREAD

**Issue by ghost** [tj/should.js#27]
Right now I am using should.equal null and should.equal undefined.

Would it be better if you could use these assertions directly?

UPDATE: I just realized that you cannot have methods to null and undefined :)

**Comment by tj** [comment]
haha yeah that's a big no unfortunately, for null or undefined checks I usually use node's assert since you can just do `assert(!err)` etc

**Comment by ghost** [comment]
I struggled to write the `should` statement for undefined tests. The following doesn't work.

```
    target.should.be.undefined();
```

I found the following solutions.

```
    (target === undefined).should.be.true()
```

if can also write it as a type check

```
   (typeof target).should.be.equal('undefined');
```

Not sure if the above is the right way, but it does work.

**Comment by fchambo** [comment]
You can use this:

`should(target).not.be.ok;`

Or this:

`should.not.exist(target)`
