### ISSUE TITLE
should.have.length() always gives length = 1

### ISSUE THREAD

**Issue by jgonera** [tj/should.js#28]
Seems it doesn't work. `lenghtOf()` too. node 0.4.10, should 0.3.2, mocha 0.0.8:

```
describe('Array length', function() {
  it('fails', function() {
    [1,2].should.have.length(2);
  });

  it('passes', function() {
    [1,2].length.should.equal(2);
  });
});
```

**Comment by jgonera** [comment]
It seems that it wraps all the arrays in another array, because this also fails:

```
['abc', 23, true].should.eql(['abc', 23, true])
```

It gives:

```
AssertionError: expected [ [ 'abc', 23, true ] ] to equal [ 'abc', 23, true ]
```

**Comment by tj** [comment]
hmm, both of these work fine for me:

``` js
['test'].should.eql(['test']);
[1,2,3].should.have.length(3);
```

**Comment by jgonera** [comment]
OK, false alarm, I'm sorry. I had a modified version of should.js in the directory, but assumed (wrongly) that `mocha --require coffee-script should spec/utils_spec.coffee` would require the global one. Sorry for the fuss.
