### ISSUE TITLE
.should.have.a.lengthOf works?

### ISSUE THREAD

**Issue by quangv** [tj/should.js#29]
In the _Readme_

```
user.pets.should.have.a.lengthOf(5)
```

does `.should.have.a.lengthOf` works? or is it only `.should.have.lengthOf` ?

**Comment by quangv** [comment]
I don't think

```
should.strictEqual(undefined, value)
should.strictEqual(false, value)
```

`.strictEqual` exists anymore either... should we just remove it from Docs?

**Comment by tj** [comment]
mgiht be busted i just use foo.should.have.length(n)

**Comment by btd** [comment]
Will be fixed in v2.
