### ISSUE TITLE
require ('should') only works once.

### ISSUE THREAD

**Issue by dominictarr** [tj/should.js#3]
here is a weird one.
    should = require('should')
    should2 = require('should') // should return the same object as previous call.
    should.should.eql(should2)

```
expected { AssertionError: ....} to equal undefined
```

would be a clever trick if you did it on purpose.

**Comment by dominictarr** [comment]
I think i've got it.

after require('should') .should gets added to every object, including the module cache, and in particularily, to the natives cache, which caches stuff like 'fs', 'path' etc.

require checks natives['should'], and if it's defined, it returns natives['should'], confusing node that it's a internal module,
then, it returns internalModuleCache['should'].exports

of course, Assertion does not have a property 'exports'

so it returns undefined!

thus, you can't should = require('should') twice in the same node process.

three fixes: 

1.
Assertion.prototype = {
  exports: assert, //a gross hack to not break require

or patch node:
2.
in ry/node/src/node.js somewhere...

```
cachedNative = internalModuleCache.hasOwnProperty(id) && internalModuleCache[id]
&
natives.hasOwnProperty(request) && natives[request]
```

etc...

or, don't use monkey patching...
3.
that(obj).should.not.monkeyPatch("!")

already have patch for 1. pull request immanent.

**Comment by tj** [comment]
bahahaha, awesome.. they should be using hasOwnProperty()

**Comment by tj** [comment]
the patch wouldn't apply, so I just chucked something in there and gave you cred in the changelog.

**Comment by dominictarr** [comment]
sweet as.
(as we say in new zealand (http://en.wikipedia.org/wiki/Sweet_as))
