### ISSUE TITLE
Does str1.should.include.string(str2) work anymore?

### ISSUE THREAD

**Issue by matthewmueller** [tj/should.js#31]
I'm getting errors in my test files and it looks like it's because `should.include.string` doesn't exist anymore. It's still in the docs, but it doesn't look like you're testing for it in should's test files. 

Is `should.include` replacing `should.include.string`? Are they equivalent?

Thanks!
Matt

**Comment by tj** [comment]
hmm the docs should mention `.should.include(str)` now, and `array.should.include(value)`

**Comment by matthewmueller** [comment]
I'm seeing:

```
Substring assertion:

'foobar'.should.include.string('foo')
```

**Comment by tj** [comment]
fixed

**Comment by sam-araiza** [comment]
doesn't seem to work anymore. however with es6 help, can do:
```'foobar'.includes('foo').should.be.true()```
