### ISSUE TITLE
includeEql throws "Object has no method 'some'"

### ISSUE THREAD

**Issue by theycallmeswift** [tj/should.js#33]
Looks like somebody had underscore installed when they wrote this method and forgot to test in isolation. No method `some` exists so this throws an error:

`['blah', 'foo', 'bar'].should.includeEql('bar') // throws!`

This is the culprit:

```
  includeEql: function(obj){
     this.assert(
       this.obj.some(function(item) { return eql(obj, item); })
       , 'expected ' + this.inspect + ' to include an object equal to ' + i(obj)
       , 'expected ' + this.inspect + ' to not include an object equal to ' + i(obj));
     return this;
   },
```

**Comment by tj** [comment]
`.some` is an `Array.prototype` method, but we should have an assertion for the method and/or being an array in there

**Comment by tj** [comment]
not a huge fan of the name either but hey :D

**Comment by theycallmeswift** [comment]
I like the method, just can't use it in its current state. Any easy fixes for this?

**Comment by tj** [comment]
well your example there works, also you could just do `['blah', 'foo', 'bar'].should.include('bar')` since primitives will be `===`

**Comment by theycallmeswift** [comment]
Ah, sorry that was just me not thinking. This is the real problem with include:

```
['blah', 'foo', 'bar-some-other-stuff'].should.include('bar')  #=> true
```

It's not exact so I was getting false positives

**Comment by tj** [comment]
hmm failed as expected for me:

```
  0)  test include() with string:
     AssertionError: expected [ 'blah', 'foo', 'bar-some-other-stuff' ] to include 'bar'
```

**Comment by theycallmeswift** [comment]
Hmmm.. thats odd. I will see if I can dig up the original code that way failing for me. Thanks for your help btw.

**Comment by tj** [comment]
maybe it's an old version of should.js or something

np

**Comment by tj** [comment]
closing until we have more info for a confirmed bug
