### ISSUE TITLE
support test for NaN

### ISSUE THREAD

**Issue by nateps** [tj/should.js#38]
As far as I can tell, there is no simple way to test for NaN.

The following works, but then the error is a not so useful "expected false to be true" when the assertion fails

```
isNaN = function(value) {
  (value != value).should.be.true
};
isNaN(NaN);
```

**Comment by TooTallNate** [comment]
JS has a global `isNaN()` function. Why not just use that?

**Comment by paulmillr** [comment]
@TooTallNate the function is buggy

```
> isNaN('test')
true
> isNaN(void 0)
true
```

**Comment by TooTallNate** [comment]
Ok good point. I guess I've never need to check explicitly for the NaN value before.

Anyways, I whipped up a quick patch:

``` diff

diff --git a/lib/should.js b/lib/should.js
index b21941a..a7b089e 100644
--- a/lib/should.js
+++ b/lib/should.js
@@ -268,6 +268,18 @@ Assertion.prototype = {
       , 'expected ' + this.inspect + ' not to be false');
     return this;
   },
+
+  /**
+   * Assert that the value is the `NaN` value.
+   */
+
+  get NaN() {
+    this.assert(
+        this.obj != this.obj
+      , 'expected ' + this.inspect + ' to be NaN'
+      , 'expected ' + this.inspect + ' to not be NaN');
+    return this;
+  },

   /**
    * Assert equal. 
```

@visionmedia merge if you'd like.

**Comment by tj** [comment]
we should be checking for typeof 'number' as well i would imagine otherwise this could have some weird false-positives

**Comment by nateps** [comment]
The typeof 'number' won't hurt, but I am pretty sure that NaN is the only thing in JavaScript that does not equal itself.

**Comment by tj** [comment]
yeah seems like it, it's probably fine

**Comment by davidchambers** [comment]
This would be useful.
