### ISSUE TITLE
Stubs and mocks

### ISSUE THREAD

**Issue by robinheghan** [tj/should.js#40]
Hi!

I would love to have the ability to be able to stub or mock any object in Should.js. I could implement this myself, but as I have limited time I would rather not waste it if no-one things stubs or mocks should be a part of Should.js at all. Before anyone says anything, yes I know I can use a third party framework like Sinon, but I'd rather this kind of functionality would be a part of the actual assert-framework than anything else.

Implementing this kind of functionality into Should allows us to automatically revert stubs when the test is done, without imposing additional syntax.

I was thinking having something like object.should.be.stubbed().should.return(42).if.called.with("id", "peterson");
which is basically three operations, stub the object, return value of 42 when called, only return already set return value if called with arguments "id" and "peterson". Then at the end of the test you might have a object.should.be.called.correctly() if it was actually called with arguments "id" and "peterson".

What do people think? Is this something people would want as a part of the Should framework, or as a standalone framework?

**Comment by kishorenc** [comment]
To me, this sounds way too verbose:

`object.should.be.stubbed().should.return(42).if.called.with("id", "peterson");`

Keeping them on separate lines using a specific mocking framework might be cleaner to me.
