### ISSUE TITLE
Objects created with Object.create(null) don't have should mixin

### ISSUE THREAD

**Issue by serby** [tj/should.js#43]
ie

```
 var foo = Object.create(null);
 assert.ok(foo.should === undefined);
```

Could this be fixed by overriding the Object.prototype.create looking for a 'null' argument[0] then internally creating the null-prototype object before adding the should mixin and returning?

Even if that did work, would you want to?

**Comment by Raynos** [comment]
```
var foo = Object.create(null);
var _should = Object.prototype.should;
_should.call(foo).be.ok;
```

**Comment by serby** [comment]
It's a pain isn't it.

I'm doing this:

```
var foo = Object.create(null);
foo.should = Object.prototype.should;
foo.should.be.a('object');
```

With all the talk on 'An object is not a hash' more devs will be doing Object.create(null) and tripping up. 

It's totally manageable, but if something can be done, do you think it should?

**Comment by serby** [comment]
This works but it might not be a good idea:

``` js
(function() {
    var defaultCreate = Object.create;
    Object.create = function() {
        var obj = defaultCreate.apply(Object, arguments);
        obj.should = Object.prototype.should;
        return obj;
    };
})();

var bar = Object.create(null);
bar.should.be.a('object');
bar.should.be.a('function'); //fail
```

Maybe 'obj.should = Object.prototype.should;'  would not be enumerable and be immutable as well.

**Comment by kilianc** [comment]
I am pretty sure this is the only way actually

``` javascript
var _should = should;
_should.obj = { foo: 'bar' };
_should.have.property('foo');
```

Extending the Object.prototype means that the .protoype itself being an Object has the should getter/setter.
That means that we cannot reach the should function this way `Object.prototype.should` without triggering the getter.

@serby I agree, this is ugly, but an hash is an hash, I don't want anything in my vanilla hash :)

**Comment by kilianc** [comment]
Another way:

``` javascript
var Assertion = require('should').Assertion;
new Assertion(Object.create(null)).be......
```
