### ISSUE TITLE
Allow _(obj).should.not.exist syntax?

### ISSUE THREAD

**Issue by al6x** [tj/should.js#45]
Right now You has to include `should = require 'should'` at the top of every spec file, to be able to use it later like `should.exist(obj)` or `should.not.exist(obj)`.

It's not very convenient, and also it's style differs from all the other assertions. Maybe it's worth to allow alternate syntax

```
_(obj).should.not.exist
```

It may be added with this code:

``` CoffeeScript
Object.defineProperty should.Assertion.prototype, 'exist',
  set: () ->
  get: () ->
    unless this.negate
      should.exist this.obj._wrapped    
    else
      should.not.exist this.obj._wrapped
  configurable: true
```

**Comment by nisaacson** [comment]
I agree with re-ordering the `should.exist` and `should.not exist`. It is much more readable and matches the other assertions much better.

**Comment by tj** [comment]
meh, I use `assert()` for this

**Comment by fabriziomoscon** [comment]
Workaround:
https://github.com/fabriziomoscon/coffeestack/blob/c30855d0426dfb86ca489f888c274c9fa4a78e03/test/init.js

**Comment by btd** [comment]
```
var should = require('should');

should(obj).have.a.length(10);
```
