### ISSUE TITLE
should.not.ifError missing

### ISSUE THREAD

**Issue by goloroden** [tj/should.js#49]
As should passes the assert module's functions, you can call

```
should.ifError(...);
```

What can _NOT_ be done at the moment is:

```
should.not.ifError(...);
```

It would be great if this was possible as well, to have the same experience for should's own functions as for the "derived" functions.

**Comment by tj** [comment]
`should.ifError()` reads really weird to me, but we do have `(function(){}).should.throw(...)` etc

**Comment by goloroden** [comment]
Well, ifError does not catch a throw (at least in my understanding). It simply checks whether the given value is truthy or falsy, and raises an exception if it is truthy.

**Comment by tj** [comment]
I dont get it, what's wrong with `foo.should.be.true` etc, or `assert(some expr)`

**Comment by goloroden** [comment]
foo (which is err in this special case) may be undefined, hence foo.should.be.... does not work

It's just that assert has a special method for checking error objects (ifError), and as should passes through all of assert's methods it would be nice if it would provide the not.x option on all of these as well, just for the sake of consistency.

That's all.

**Comment by mx4492** [comment]
In the meantime, `should.not.exist(error)` works.
