### ISSUE TITLE
should.throw() neglected

### ISSUE THREAD

**Issue by swissmanu** [tj/should.js#51]
i have following _abstract_ class defined:

```
var util = require('util')
    ,EventEmitter = require('events').EventEmitter;

var GuideFetcher = function() {
    var _self = this;
    EventEmitter.call(this);

    this.getFestivals = function() { throw new Error('Overwrite getFestivals!'); };
    this.getArtists = function() { throw new Error('Overwrite getArtists!'); };
};
util.inherits(GuideFetcher, EventEmitter);

module.exports = GuideFetcher;
```

the test cases are implemented with mocha using should.js as followed:

```
var GuideFetcher = require('../guidefetcher/guidefetcher');

describe('GuideFetcher', function() {
    var guideFetcher = new GuideFetcher();

    describe('#getFestivals()', function() {
        it('should throw an "Overwrite getFestivals()" exception', function() {
            guideFetcher.getFestivals().should.throw();
        })
    })

    describe('#getArtists()', function() {
        it('should throw an "Overwrite getArtists()" exception', function() {
            guideFetcher.getArtists().should.throw();
        })
    })
})
```

unfortunatly, the error is not catched by should.js, instead it goes directly to my console output.

is this an known issue?

thanks,
manuel

**Comment by tj** [comment]
remember that `.should.throw()` invokes the function, so you may want to wrap those in an closure or `guideFetcher.getFestivals.should.throw()`

**Comment by swissmanu** [comment]
of course it does %-) thank you for the clearification!
but how can i check if a method call using specific parameters would throw an error?

`guideFetcher.getArtist('xy').should.throw()` would refer again to the return value of `getArtists`, right?

**Comment by tj** [comment]
that's correct, you should wrap it:

```
(function(){
  foo.bar(baz)
}).should.throw(...)
```

**Comment by swissmanu** [comment]
thats acutally pretty straight forward. thank you! never thought about solving it like this ;)

**Comment by kellyjandrews** [comment]
:+1:  for finding this gem!
