### ISSUE TITLE
Suggestion: should.eql() static method

### ISSUE THREAD

**Issue by debonet** [tj/should.js#52]
Sometimes it would be convenient, when you don't know the argument types, to have a static version of not-strict-equals.

So that you can do this:

```
{a:1,b:2}.should.eql({b:2,a:1});
```

or do this

```
should.eql({a:1,b:2},  {b:2,a:1});
```

as well as

```
should.eql(null, 0);
should.eql(undefined, 0);
should.eql(undefined, null);
should.eql("1", 1);
...
```

etc.

**Comment by debonet** [comment]
In fact, it would be nice if all `.should` methods were also available statically. 

Perhaps adding the english sugar of `these.should.be` as an alias for the global `should`, might make it even more palatable, so you'd have syntax like:

```
these.should.be.eql("1",1);

these.should.not.exist(error, response);

these.should.be.ok(itworked, noproblems);

these.should.be.truthy(isItChristmasYet);

...
```

**Comment by tj** [comment]
I think if you're needing that you should just drop to node's `assert` `assert(foo === undefined)` etc is nicer IMO

**Comment by debonet** [comment]
But `assert` doesn't give you `object.should.eql()`'s functionality. i.e.

```
var assert=require('assert');
assert({a:1} === {a:1});
```

fails, but if we did:

```
var should = require('should');

should.eql = function(x1,x2){
    if (x1===null || typeof(x1) === "undefined"){
        return should.not.exist(x2);
    }

    return x1.should.eql(x2);
};

should.eql({a:1}, {a:1});
```

it passes.

**Comment by tj** [comment]
assert has `assert.deepEquals()` or something, it's just a really ugly name

**Comment by rafmagana** [comment]
I just did a pull request, the patch will let you to do this:

```
 {a:1,b:2}.should.eql({b:2,a:1});
```

but via include()

```
  {a:1,b:2}.should.include({b:2,a:1}); // true
```

but will let you to check for some properties/values

```
  {a:1,b:2}.should.include({a:1}); // true
```

Besides I added a helper to check deep equality which I use to check if an object is equal to another, it's not exposed to the main API but we can do it so we can use eql();
