### ISSUE TITLE
should.equal fails when comparing dates

### ISSUE THREAD

**Issue by ericchaves** [tj/should.js#63]
Hi guys,

Using should.equal with Date objects seems to be failing. 

``` javascript
var date = new Date();
date.should.equal(date);

AssertionError: expected 1335443601886 to equal Thu, 26 Apr 2012 12:33:21 GMT
```

This happens because "should" value (the actual value) is obtained using the valueOf() function (should.js line 81) and the "equal" function does not follow the same approach, comparing the valufOf(actual) with the actual object directly (should.js line 303). In case of date objects since valueOf returns a number the equality fails.

I fix it by performing the same process of value comparison changing the equal function to (line 303):

``` javascript
        Object(val).valueOf() === this.obj
```

Not sure if this has broader implication on the framework thou.

Cheers,

Eric

**Comment by c4milo** [comment]
I'm using v1.2.1 and running into this same problem.

**Comment by ben-lin** [comment]
same here, v1.2.1

**Comment by zerobase** [comment]
@c4milo @ben-lin 
I use `eql` instead of `equal` (strict equal).
