### ISSUE TITLE
instanceof

### ISSUE THREAD

**Issue by nijikokun** [tj/should.js#68]
`instanceof` is bad and you should feel bad for using it. Here at least. In the other places... it's more suited because you implicitly state it's `instanceof` but here it really isn't.

https://github.com/visionmedia/should.js/blob/master/lib/should.js#L547
https://github.com/visionmedia/should.js/blob/master/lib/should.js#L675

`Object.prototype.toString.call([Object])`

**Comment by tj** [comment]
meh I dont do cross-context stuff really so it doesn't matter to me, we could change the one to `Array.isArray()`

**Comment by nijikokun** [comment]
True, but why prefer that over a cross-compat one?

**Comment by tj** [comment]
should isn't built for the browser, it would fail in lots of browsers because of the getters already

**Comment by nijikokun** [comment]
True, I suppose then the `Array.isArray()` is fine unless you want strict equality.
