### ISSUE TITLE
Browserification?

### ISSUE THREAD

**Issue by nearstate** [tj/should.js#69]
This may be a BCAK error, but trying to browserify my tests (in mocha + should), I get 

```
SyntaxError: Error while loading entry file "/samples/gbL.jsMop/node_modules/should/lib/should.js": Unexpected token: punc (()
  at line 0:1045 in expression:


var util=require("util"),http=require("http"),assert=require("assert"),AssertionError=assert.AssertionError,statusCodes=http.STATUS_CODES,eql=require("./eql"),i=util.inspect;exports=module.exports=assert;exports.version="0.6.3";exports.exist=function(obj,msg{if(null==obj){throw new AssertionError({message:msg||"expected "+i(obj)+" to exist",stackStartFunction:should.exist})}};exports.not={};exports.not.exist=function(obj,msg){if(null!=obj){throw new AssertionError({message:msg||"expected "+i(obj)+" to not exist",stackStartFunction:should.not.exist})}};Object.defineProperty(Object.prototype,"should",{set:function(){},get:function(){return new Assertion(Object(this).valueOf())},configurable:true});var Assertion=exports.Assertion=function Assertion(obj){this.obj=obj};Assertion.prototype={exports:exports,assert:function(expr,msg,negatedMsg,expected){var msg=[this.negate?negatedMsg:msg][0],ok=[this.negate?!expr:expr][0];if(!ok){throw new AssertionError({message:msg,actual:this.obj,expected:expected,stackStartFunction:this.assert})}},(get an(){return this}),
```

which is complaining about a part of should.js here:

``` javascript
/**
   * Dummy getter.
   *
   * @api public
   */

  get an() {
    return this;
  },
```

Do you think this is an issue with what I am trying to do, with should, or with browserify?

**Comment by tj** [comment]
you cant really use this in anything but modern browsers anyway

**Comment by nearstate** [comment]
Yeah, is should basically only focused on node then? I kind of assumed that because Mocha targets both browser and node and they favour should.js in their documentation, that there would be a browser-based way to use should. No?

**Comment by tj** [comment]
you can use anything you want with mocha, should is just an example of an assertion lib, but most browsers lack the features used

**Comment by tj** [comment]
check out "chai" or expect.js

**Comment by nearstate** [comment]
: ( I know, but I think your library is a good one.
Do you want me to fork it and retro-fit for older browsers?

**Comment by tj** [comment]
it cant work in older browsers with the same API, that's the thing, but that's why expect.js is around

**Comment by nearstate** [comment]
I think there might be a way
------Original Message------
