### ISSUE TITLE
Should causes async Mocha tests to timeout

### ISSUE THREAD

**Issue by tgvashworth** [tj/should.js#71]
I'm running Mocha in watch mode, compiling CoffeeScript tests.

``` coffeescript
# This fails by timing out
it 'should be able to grab qba6sms/published from Typekit', (done) ->
    $.getJSON 'http://typekit.com/api/v1/json/kits/qba6sms/published?callback=?', (data, txt, xhr) ->
      data.should.be.ok
      done()
```

``` coffeescript
# This does not fail
it 'should be able to grab qba6sms/published from Typekit', (done) ->
    $.getJSON 'http://typekit.com/api/v1/json/kits/qba6sms/published?callback=?', (data, txt, xhr) ->
      assert.ok data
      done()
```

I'm not sure what's up – am I doing something wrong, or is it a bug?

**Comment by tj** [comment]
what's the compiled code? maybe CS is fucking it up

**Comment by tgvashworth** [comment]
Could it be the returns?

``` javascript
return it('should be able to grab things from Typekit', function(done) {
  return $.getJSON('http://typekit.com/api/v1/json/kits/qba6sms/published?callback=?', function(data, txt, xhr) {
    data.should.be.ok;
    return done();
  });
});
```

**Comment by tj** [comment]
they shouldn't matter

**Comment by tgvashworth** [comment]
Didn't think so, any other ideas? Mocha's compiling it on the fly... I might try compiling it with coffee and running the tests on that code.

**Comment by tgvashworth** [comment]
Just tried chai – `expect(data)` works great, but `should` times out.

**Comment by tgvashworth** [comment]
``` coffeescript
describe 'typekit', () ->
  it 'should be able to fetch the example kit', (done) ->
    this.timeout 8 * 1000
    typekit.get 'http://typekit.com/api/v1/json/kits/qba6sms/published?callback=?', (data) ->
      data.kit.id.should.equal 'qba6sms'
      done()
  it 'should be able to fetch my kits', (done) ->
    this.timeout 8 * 1000
    typekit.get 'http://typekit.com/api/v1/json/kits?token=xxxxx&callback=?', (data) ->
      data.should.be.a 'object'
      done()
```

Top works, bottom times out. When I add `data.should.be.a 'object'` to the top, it times out. This ain't the CS – exact same problem with raw JS tests.

**Comment by tj** [comment]
some browsers don't really properly expose uncaught exceptions that's probably why it's timing out

**Comment by tgvashworth** [comment]
I'm using Mocha in watch mode (although it fails in normal mode too):

``` make
@./node_modules/.bin/mocha -w -R min -r should --compilers coffee:coffee-script
```

**Comment by tj** [comment]
oh i see this is with node, i'll look into it soon

**Comment by tgvashworth** [comment]
Thanks.

Some more info, for that last bit of code:
First example: `typeof data.kit.id.should` is `object`
Second example: `typeof data.should` is `undefined`

In both cases `data` is an `object`.

**Comment by enyo** [comment]
Having the exact same problem. Tests timeout with should. Using the latest versions of node, mocha and should.

**Comment by enyo** [comment]
I have now tested it with chai and without should and experienced the same problem... So it seems to be more related to mocha than should.

**Comment by wprater** [comment]
Having the same issue, where a failed `should` assertion causes mocha test to time out and never call done.  This happens within a return mongoose promise.

**Comment by btd** [comment]
Show me your code.

**Comment by wprater** [comment]
model

```
schema.statics.ignite = function (foo) {
  var prom = new mongoose.Promise();
  setTimeout(function () {
    prom.resolve(null, 'foobar');
  } , 500);
  return prom;
};
```

test

```
  it('failing test in resolved promise times out', function (done) {
    Model.ignite('foo')
    .then(function (flare) {
      true.should.be.false;
      done();
    }, done);
  });
```

**Comment by btd** [comment]
Not sure about mongosee promises, but q.js **require** to add to final promise .done() or return it. Maybe the same with mongoose promises? In should there is nothing to block.

**Comment by wprater** [comment]
Ahh, thanks @btd , I needed to add the `#end` to finalized the chain.  But there is not chain ;)  I thought you only needed to call `end` if you were chaining `then`'s.

```
it('failing test in resolved promise times out', function (done) {
    Model.ignite('foo')
    .then(function (flare) {
      true.should.be.false;
      done();
    }, done)
    .end();
  });
```

**Comment by nicohvi** [comment]
+1

**Comment by leftstick** [comment]
The thing you are encountering is nothing to do with `mocha`, `should` or even `chai`. It caused by promise.

When the `should` fails, `Promise` turn the process into `reject` state, instead throw the error directly. 

Just modify your code as following:

``` javascript
it('promise', function(done) {
        new Promise(function(resolve, inject){
            setTimeout(function(){
                resolve(false);
            }, 20);
        })
            .then(function(state) {
                state.should.be.ok;
                done();
            })
            .catch(done);
    });
```

You have to `catch` the error yourself
