### ISSUE TITLE
Feature request: show test file name and line number on error

### ISSUE THREAD

**Issue by willhlaw** [tj/should.js#78]
I am using mocha and should for node testing and was wondering about this feature. Saw others asking for it on on the mocha repo and there seems to be a solution for chai. https://github.com/visionmedia/mocha/issues/482

Any plans or ideas for exposing at least the file name? 

Thanks.

**Comment by tj** [comment]
I can't think of any non-hacky way off the top of my head to provide the test case's lineno since mocha just accepts arbitrary files. you could potentially grep the stack trace and see if the file is one of those passed. that should work
