### ISSUE TITLE
should.exist and should.not.exist errors does not have stacktraces

### ISSUE THREAD

**Issue by faridnsh** [tj/should.js#84]
The title says it all, have tested this in `0.6.3` and `1.1.0`. The error is like `AssertionError: expected undefined to exist` without any  stack trace.

**Comment by kimptoc** [comment]
Doh - so thats why I am getting those one liners.  I am using 1.2.0

**Comment by faridnsh** [comment]
It's fixed in v1.2.1

**Comment by kimptoc** [comment]
Thanks :)
