### ISSUE TITLE
should.have.property('name', undefined)

### ISSUE THREAD

**Issue by l8nite** [tj/should.js#87]
I want to actually check that I have a property with value undefined.

I think right now the property check is using undefinedness to determine if the second argument was passed in (when instead it should probably check arguments.length).

**Comment by tj** [comment]
you cant use properties on undefined or null. IMO github.com/visionmedia/better-assert is much cleaner for these, `assert(foo.bar == null)`

**Comment by l8nite** [comment]
I'll close this since there are alternatives, but what property is being used here?
