### ISSUE TITLE
Should node be called

### ISSUE THREAD

**Issue by wdavidw** [tj/should.js#90]
Hi & thanks for your nice module
Would be nice to validate some code isn't executed, something as `should.not.be.called`, What do you think ?

**Comment by tj** [comment]
im not a fan of "spies" personally, I dont think they really test anything significant, but I would just do `foo.bar = function(){ assert(0 && "should not be called") }`

**Comment by wdavidw** [comment]
Neither am I, but I just face a situation where that would have detected a bug. Thanks for answering so promptly, do you want me to prepare a pull request ?

**Comment by btd** [comment]
It is things for `sinon.js`. If it is required, better to write some plugin, but do not include all things in should.js
