### ISSUE TITLE
\t | equal check throws, although there's no difference shown

### ISSUE THREAD

**Issue by buschtoens** [tj/should.js#92]
I was doing the tests on my badge and [this error](https://travis-ci.org/silvinci/component-badge/builds/3812407) caught my attention. should.js doesn't show which part of the string is unequal.

excerpt of [`test.js`](https://github.com/silvinci/component-badge/commit/066e413f72d70e8d6298e1a9fc1df51b70e8a052)

``` javascript
function fixture(name) {
    return fs.readFileSync(path.join(__dirname, "fixtures", name), "utf8").replace(/\r/g, '');
}
badge(500, { subtitlePos: "right" }).should.equal(fixture("positioning.svg"));
```

I think should.js complains about `\r` or `\n`, but it isn't shown.

**Comment by buschtoens** [comment]
Comparing the length of the strings shows, that one is two chars longer. But I can't see where those extra chars are. They're not at the start and not at the end.

**Comment by buschtoens** [comment]
``` javascript
var expected = fixture("positioning.svg");
var found = [], diff = 0;
badge(500, { subtitlePos: "right" }).split("").forEach(function(actualChar, index) {
    var expectedChar = expected.charAt(index+diff);
    if(actualChar != expectedChar) {
        found.push({ actual: actualChar, expected: expectedChar });
        diff++;
    }
});
console.log(found);
```

```
[ { actual: '<', expected: '\t' },
  { actual: '<', expected: '\t' },
  { actual: 'r', expected: '<' },
  { actual: '<', expected: '\t' },
  { actual: 'c', expected: '<' },
  { actual: '<', expected: '\t' },
  { actual: 'p', expected: '<' },
  { actual: '<', expected: '\t' },
  { actual: 'p', expected: '<' },
  { actual: '<', expected: '\t' },
  { actual: 't', expected: '<' },
  { actual: '<', expected: '\t' },
  { actual: 't', expected: '<' },
  { actual: '<', expected: '\t' } ]
```

Seems like should.js has trouble displaying tabs.

**Comment by buschtoens** [comment]
My [error is fixed](https://travis-ci.org/silvinci/component-badge/builds/3812581) now. I accidentally double indented `positioning.svg`. Nevertheless the issue remains. should.js doesn't highlight errors on tabs.

**Comment by btd** [comment]
It is mocha issue. Should.js just complain that it is not equal, test runner create diff for you.

So it is better to duplicated issue to mocha.
