### ISSUE TITLE
receiving lots of timeouts, but no errors

### ISSUE THREAD

**Issue by mayorbyrne** [tj/should.js#96]
You'll really have to bear with me.  I'm pretty new to node, and especially new to mocha and the should module.  However, here's the problem I'm having:

Once I connect to a server (using [json-socket](https://github.com/sebastianseilund/node-json-socket)), I attempt to send a message using the following.  The server is set up to send the message 'server sends this' back once it receives a message.  Using the code below, the test passes.

``` js
it('should get message', function(done){
    client.sendMessage({"anything":"anything"});
    client.on('message', function(data){
                console.log(data); //prints "server sends this"
        data.should.equal('server sends this');
        done();
    });
});
```

Now, if I change it do data.should.not.equal('server sends this'), I no longer pass the test, but instead receive a timeout error.  The same thing happens if I try data.should.exist();  I'm not sure why I'm seeing only timeout errors when it relates to this.  Also, console.log(data.should.equal('server sends this')); gives me: { obj: 'server sends this' }.

**Comment by btd** [comment]
It is probably test runner issue. Reopen if still persist.
